export default {
    btn_burger: "react-burger-menu-btn",
    btn_cart: "shopping_cart_container",
    title_product: "//span[.='Products']",
    dropdown_sort: "product_sort_container",
    badge_cart: "shopping_cart_badge",

    // Product List
    img_backpack: "[data-test='inventory-item-sauce-labs-backpack-img']",
    img_bike_light: "[data-test='inventory-item-sauce-labs-bike-light-img']",
    img_tshirt: "[data-test='inventory-item-sauce-labs-bolt-t-shirt-img']",
    img_jacket: "[data-test='inventory-item-sauce-labs-fleece-jacket-img']",
    img_onesie: "[data-test='inventory-item-sauce-labs-onesie-img']",
    img_red_tshirt: "[data-test='inventory-item-test.allthethings()-t-shirt-(red)-img']",
    title_backpack: "//div[.='Sauce Labs Backpack']",
    title_bike_light: "//div[.='Sauce Labs Bike Light']",
    title_tshirt: "//div[.='Sauce Labs Bolt T-Shirt']",
    title_jacket: "//div[.='Sauce Labs Fleece Jacket']",
    title_onesie: "//div[.='Sauce Labs Onesie']",
    title_red_tshirt: "//div[.='Test.allTheThings() T-Shirt (Red)']",
    desc_backpack: "//div[contains(text(),'carry.allTheThings() with the sleek,')]",
    desc_bike_light: `//div[contains(text(),"A red light isn't the desired state in testing")]`,
    desc_tshirt: "//div[contains(text(),'Get your testing superhero on with')]",
    desc_jacket: `//div[contains(text(),"It's not every day that you come across")]`,
    desc_onesie: "//div[contains(text(),'Rib snap infant onesie for the junior')]",
    desc_red_tshirt: "//div[contains(text(),'This classic Sauce Labs t-shirt')]",
    price_backpack: "//div[.='$29.99']",
    price_bike_light: "//div[.='$9.99']",
    price_tshirt: "//div[.='$15.99']",
    price_jacket: "//div[.='$49.99']",
    price_onesie: "//div[.='$7.99']",
    price_red_tshirt: "//div[.='$15.99']",
    btn_add_to_cart_backpack: "add-to-cart-sauce-labs-backpack",
    btn_add_to_cart_bike_light: "add-to-cart-sauce-labs-bike-light",
    btn_add_to_cart_tshirt: "add-to-cart-sauce-labs-bolt-t-shirt",
    btn_add_to_cart_jacket: "add-to-cart-sauce-labs-fleece-jacket",
    btn_add_to_cart_onesie: "add-to-cart-sauce-labs-onesie",
    btn_add_to_cart_red_tshirt: "[id='add-to-cart-test.allthethings()-t-shirt-(red)']",
    btn_remove_backpack: "remove-sauce-labs-backpack",
    btn_remove_bike_light: "remove-sauce-labs-bike-light",
    btn_remove_tshirt: "remove-sauce-labs-bolt-t-shirt",
    btn_remove_jacket: "remove-sauce-labs-fleece-jacket",
    btn_remove_onesie: "remove-sauce-labs-onesie",
    btn_remove_red_tshirt: "remove-sauce-labs-bolt-t-shirt",

    //footer
    icon_twitter: "//a[.='Twitter']",
    icon_facebook: "//a[.='Facebook']",
    icon_linkedin: "//a[.='Twitter']",
    footer_text: "//div[@data-test='footer-copy']",
}